Update AbstractXapiRestController class path
Running this plugin on XNAT >=1.8.5 produces the following error:

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [de.htwberlin.cbmi.fhir.XnatOnFhirPlugin]; nested exception is java.io.FileNotFoundException: class path resource [org/nrg/xdat/rest/AbstractXapiRestController.class] cannot be opened because it does not exist

Fix by updating references to the new class path: org.nrg.xapi.rest.AbstractXapiRestController